[package]
name = "zed_gdscript"
version = "0.5.0"
edition = "2021"
publish = false
license = "MIT"

[lib]
path = "src/gdscript.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.6.0"

[profile.release]
codegen-units = 1 # Allows LLVM to perform better optimization.
lto = true # Enables link-time-optimizations.
opt-level = "s" # Prioritizes small binary size. Use `3` if you prefer speed.
strip = true # Ensures debug symbols are removed.

